export const LITE_INPUT_REQUEST = "LITE_INPUT_REQUEST"
export const LITE_INPUT_SUCCESS = "LITE_INPUT_SUCCESS"
export const LITE_INPUT_FAIL = "LITE_INPUT_FAIL"

export const ORDER_INPUT_REQUEST = "ORDER_INPUT_REQUEST"
export const ORDER_INPUT_SUCCESS = "ORDER_INPUT_SUCCESS"
export const ORDER_INPUT_FAIL= "ORDER_INPUT_FAIL"

